### ISSUE TITLE
Basic Skeleton Classes

### ISSUE THREAD

**Issue by davidlevitsky** [cpe305/fall2016-project-davidlevitsky#1]
There need to be two main skeleton classes that the rest of the activity: an Event class and a Data class. 

An Event class will contain at minimum the following characteristics, which should be private, as well as getters and setters to access these characteristics:
time, location, participants, date, and a name of the event

A Data class will act as a database to hold all created events and should contain, at minimum:
a list of events, number of events, and a sorting feature so events are added in the correct order. I will implement the sorting feature myself.

**Comment by Quangder** [comment]
Finished the class
